version: "3"
services:
  app:
    image: "${CONTAINER_IMAGE}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==public]
    environment:
      PORT: "80"
      DB_URI: ${DB_URI}
      TEST: ${TEST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: devops@isuvorov.ru

    networks:
      - proxy
networks:
  local:
  proxy:
    external:
      name: nginx-proxy
